name: bloc_basis
description: Flutter BLoC Basis.
version: 1.0.2
homepage:

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter:

dependencies:
  equatable:
  flutter:
    sdk: flutter
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
